-- Rollback: 007_apply_security_rls_policies.down.sql
DROP FUNCTION IF EXISTS public.get_ceo_vault_launch_access(UUID) CASCADE;
DROP FUNCTION IF EXISTS public.ceo_vault_access_check(UUID) CASCADE;
DROP FUNCTION IF EXISTS auth.is_admin() CASCADE;

-- Table level RLS can be disabled if needed
ALTER TABLE ai_decision_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE meta_snapshots DISABLE ROW LEVEL SECURITY;
ALTER TABLE intel_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE feature_usage_daily DISABLE ROW LEVEL SECURITY;
ALTER TABLE search_telemetry DISABLE ROW LEVEL SECURITY;
ALTER TABLE build_ratings DISABLE ROW LEVEL SECURITY;
ALTER TABLE jumpshot_ratings DISABLE ROW LEVEL SECURITY;
ALTER TABLE cap_breaker_matrix DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_favorite_jumpshots DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_saved_builds DISABLE ROW LEVEL SECURITY;
ALTER TABLE builds DISABLE ROW LEVEL SECURITY;
ALTER TABLE jumpshot_recipes DISABLE ROW LEVEL SECURITY;
ALTER TABLE jumpshot_components DISABLE ROW LEVEL SECURITY;
ALTER TABLE animations DISABLE ROW LEVEL SECURITY;
ALTER TABLE badge_requirements DISABLE ROW LEVEL SECURITY;
ALTER TABLE creator_verifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE game_titles DISABLE ROW LEVEL SECURITY;
